[tool.bumpversion]
current_version = "0.0.9"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "sra_collector/__init__.py"

[[tool.bumpversion.files]]
filename = "tests/test_cli.py"