[tool.bumpversion]
current_version = "0.0.10"

[[tool.bumpversion.files]]
filename = "pyproject.toml"

[[tool.bumpversion.files]]
filename = "csra/__init__.py"

[[tool.bumpversion.files]]
filename = "tests/test_cli.py"