name: build-and-test
on: [ push ]
jobs:
  test-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Dependencies & Unit Tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: python -m unittest discover
      - run: python -m build