name: test-build-publish
on: [ push ]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Dependencies & Unit Tests
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'
      - run: pip install -r requirements.txt
      - run: pip install -e .
      - run: python -m unittest discover
      - run: python -m build
  pypi-publish:
    runs-on: ubuntu-latest
    needs: test-build
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/csra
    steps:
      - name: Bump Version
        run: pip install bump-my-version && bump-my-version bump patch
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
