name: pypi-publish
on:
  workflow_run:
    workflows:
      - build-and-test
    types:
      - completed
jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/csra
    steps:
      - name: Bump Version
        run: bump-my-version bump patch
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
      - uses: pypa/gh-action-pypi-publish@release/v1
