name: test-build-publish
on: [ push ]
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Tests & Build
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
      - run: pipx install poetry
      - run: poetry install
      - run: poetry run pytest

  publish:
    runs-on: ubuntu-latest
    needs: test-build
#    if: github.ref == 'refs/heads/main'
    permissions:
      id-token: write
      contents: write
    environment:
      name: pypi
      url: https://pypi.org/project/csra
    steps:
      - name: Build Package
        uses: actions/checkout@v4
      - run: pipx install poetry
      - run: poetry install
      - run: poetry run bump-my-version bump patch

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

      - uses: pypa/gh-action-pypi-publish@release/v1

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 🔼 Bump package version
          commit_user_email: actions@github.com
          commit_author: GitHub Actions <actions@github.com>